// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvwqlweixgfajvtokmpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2d3Fsd2VpeGdmYWp2dG9rbXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjEzOTMsImV4cCI6MjA2MTkzNzM5M30.cW8RoSQDifjKp3-LcySM4uKqCezuAtTNyZUiGqfwoHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);